inicio/urls.py
# De esta forma voy importando las funcionalidades de las views una por una, pero se puede hacer demasiado largo
# from inicio.views import bienvenida, fecha_y_hora, saludo, mitemplate, mitemplate2, condicional_loop, crear_auto, home, listado_autos

#Esta forma es más práctica
from inicio import views    # sólo tengo qyue agregar views a los urls
from django.urls import path

app_name = 'inicio' # creo esta variable para luego acomodar el tema de los links. Esta variable contiene el nombre de mi aplicacion
                    # y la modificacion se hace sobre el urls.py propio de la aplicación. 

urlpatterns = [
    path('bienvenida', views.bienvenida, name = 'bienvenida'),
    path('', views.home, name = 'home'),
    path('fecha-y-hora/', views.fecha_y_hora,name = 'datetime'),
    path('saludo/<nombre>/<apellido>/', views.saludo, name = 'saludo'), 
    path('mitemplate/', views.mitemplate, name = 'mitemplate'),
    path('mitemplate2/', views.mitemplate2, name = 'mitemplate2'),
    path('condicional_loop/', views.condicional_loop, name = 'condicional_loop'),
    #,path('crear_auto/<str:marca>/<str:modelo>/<int:anio>', crear_auto, name = 'crear_auto') # opcion 1
    path('autos/', views.listado_autos, name='listado_autos')
    ,path('autos/crear', views.crear_auto, name = 'crear_auto')
    ,path('autos/<int:id_auto>', views.ver_auto, name = 'ver_auto')
    ,path('autos/<int:id_auto>/eliminar', views.eliminar_auto, name = 'eliminar_auto')
    ,path('autos/<int:id_auto>/editar', views.editar_auto, name = 'editar_auto')
  
    ]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include

# aca puedo ver la modificacion automatica que se hizo cuando cambié la carpeta de lugar
# el tema es que me lo trae automaticamente como ..inicio.views (dos carpetas por arriba de inicio) y yo necesito que sea directo
#desde inicio, y por eso queda finalmente: inicio.views (ver aquí abajo)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("inicio.urls"))    # include el nombre de la aplicacion (inicio) y el archivo donde tengo los "links" (urls)
]

inicio/models.py
from django.db import models

class Auto(models.Model): #Creo una clase X, pero con herencia models.Model
    marca = models.CharField(max_length = 20)
    modelo = models.CharField(max_length = 20)
    anio = models.IntegerField()
    
    def __str__(self):
        return f'Auto({self.id}): {self.marca} {self.modelo}'

inicio/forms.py
### AQUI SE GUARDAN LOS FORMULARIOS
# mira que se parece a models pero mejor
from django import forms

class FormularioBaseAuto(forms.Form):
    marca = forms.CharField(max_length=20)
    modelo = forms.CharField(max_length=20)
    anio = forms.IntegerField()

class CrearAuto(FormularioBaseAuto):
    ...
    
class EditarAuto(FormularioBaseAuto):
    ...  

class BuscarAuto(forms.Form):
    marca = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'placeholder': 'Ford, Fiat, Chevrolet...'}))
    modelo = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'placeholder': 'Uno, K, 206...'}))
    

inicio/views.py
### Acá vamos a estar trabajando nuestras vstas ###

# Una vista es una función
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from django.shortcuts import render, redirect
from inicio.models import Auto
import random
from inicio.forms import CrearAuto, BuscarAuto, EditarAuto


def home(request):
    #return HttpResponse('<h1> Bienvenidos! </h1>')
    return render (request, 'inicio/home.html', {})

def bienvenida(request):
    #return HttpResponse('<h1> Bienvenidos! </h1>')
    return render (request, 'inicio/bienvenida.html', {})


def fecha_y_hora(request):
    fecha_y_hora = datetime.now()
    return HttpResponse(f'<h1> Acá se muestra la hora actual </h1>\n {fecha_y_hora}')

def saludo(request, nombre, apellido):  
    # path dinamico
    nombre_formateado = nombre.title
    apellido_formateado = apellido.title
    return HttpResponse(f'<h1> Hola {nombre} {apellido}  ! como te va?  </h1>')

# --------------------------------------------------------------------------------------------
def mitemplate(request):

# VERSION 1 - ORIGINAL 

    # with open('mitemplate.html') as archivo_abierto:
    #     template = Template(archivo_abierto.read())
    
    # contexto = Context({'nombre':'pepe'})
    # template_renderizado = template.render(contexto)
    
    # #return HttpResponse(template_renderizado)
    # return render(request, 'mitemplate.html', {'nombre':'pepe'} ) # el contexto es opcional

# VERSION 3 - LA QUE QUEDA!!!!!
    return render (request, 'inicio/mitemplate.html', {'nombre':'pepe'} ) #request, template, contexto (opcional)


# --------------------------------------------------------------------------------------------
def mitemplate2(request):

# VERSION 2 - NUEVA VERSION MEJORADA
   
    # Cambié el BASE DIR que es algo de python, pero no de DJANGO, entonces necesito usar el loader
    template = loader.get_template('inicio/mitemplate2.html')
    
   # Ya no necesitamos crear un contexto pq estamos trabajando con el loader.get_template
   # directamente en lugar del context tenemos que colocar el diccionario que queremos ver
    template_renderizado2 = template.render({'nombre': 'Gremlina'})
    
    # return render(request, 'mitemplate.html')
    return HttpResponse(template_renderizado2)

def condicional_loop(request):
    
    return render (request, 'inicio/condicional_loop.html',  {
      'nombre':'Ricardo',
      'mis_elementos':[22],
      'numero': 2,
      'numeros': list(range(15))
      }  ) 

# Todo lo que es views y url se debe combinar en un mismo lugar llamado "APLICACIÓN"

#---------------------------------------------------------------------------------------------
# opcion 1
# def crear_auto(request, marca, modelo, anio):
#     # de la terminal interactiva me traigo el codigo
    
#     #auto = Auto(marca = random.choice(['Ford','Fiat','Renault']), modelo = 'wtf', anio = random.choice([2020,2021,2023]))
#     auto = Auto(marca = marca, modelo = modelo, anio = anio)
#     auto.save()
    
#     return render(request, 'inicio/auto_correctamente_creado.html', {'auto':auto})
#_---------------------------------------------------------------------------------------

# Opcion 2 crear auto - post/get sin formulario
# def crear_auto(request):
    
#     ###### VEAMOS QUE EL GET SE PUEDE USAR, PERO NO SE RECOMIENDA  ######
    
#     #Verifica los datos que recibes
#     print('*****************************')
#     print('GET', request.GET)  # Verifica qué datos estás recibiendo
#     print('POST', request.POST)
#     print('******************************')

    # marca = request.GET.get('marca')
    # modelo = request.GET.get('modelo')
    # anio = request.GET.get('anio')

    # # Para evitar el error de los not null
    # if marca and modelo and  anio:
    #    # Si los parámetros son válidos, guarda el auto
    #     auto = Auto(marca=marca, modelo=modelo, anio=anio)
    #     auto.save() 

    # # Renderiza la página de éxito
    # return render(request, 'inicio/crear_auto.html', {})

###### AHORA LO HACEMOS CON EL POST
# def crear_auto(request):
    
#     marca = request.POST.get('marca')
#     modelo = request.POST.get('modelo')
#     anio = request.POST.get('anio')

#     # si la request viene por POST sí lo creo, si viene por GET no
#     if request.method == 'POST':
        
#     # Para evitar el error de los not null
#         if marca and modelo and  anio:
#         # Si los parámetros son válidos, guarda el auto
#             auto = Auto(marca=marca, modelo=modelo, anio=anio)
#             auto.save() 

#     # Renderiza la página de éxito
#     return render(request, 'inicio/crear_auto.html', {})

# -----------------------------------------------------------------------------
# Opción 3 - Formulario (inicio/forms.py)
    #Para esto tengo que hacer el import forms
    
def crear_auto(request):
    
    print('*****************************')
    
    formulario = CrearAuto()
    
    # si la request viene por POST sí lo creo, si viene por GET no
    if request.method == 'POST':
        formulario = CrearAuto(request.POST)   
        if formulario.is_valid():
            
            data = formulario.cleaned_data
            
            auto = Auto(marca=data.get('marca'), modelo=data.get('modelo'), anio=data.get('anio'))
            auto.save() 
            
            return render(request, 'inicio/home.html',{})

    # Renderiza la página de crear auto
    return render(request, 'inicio/crear_auto.html', {'formulario':formulario}) #mi contexto ahora es el formulario

# --------------------------------------------------------------------------------------------

# Opción 1 - Traer todo sin buscar
# def listado_autos(request):
#     listado_autos = Auto.objects.all() # quiero todos los objetos de auto

# Opción 2 - si quiero filtrar el auto que obtengo mediante una busqueda
# def listado_autos(request):
#     buscar_marca = request.GET.get('marca')
#     #buscar_modelo = request.GET.get('modelo')
    
#     if buscar_marca:
#         listado_autos = Auto.objects.filter(marca__icontains = buscar_marca) #filtra que la marca del auto CONTENGA los caracteres que busco
#     else: 
#         listado_autos = Auto.objects.all()


    
    # # Opcion 3 - Usando el GET
    # listado_autos = Auto.objects.filter(marca__icontains = buscar_marca, modelo__icontains = buscar_modelo)
    # return render(request, 'inicio/listado_autos.html', {'listado_autos':listado_autos})
  
    ### Modificacion de chatgpt - me gusta mas ###
    # Obtener los parámetros de búsqueda desde la URL
    # buscar_marca = request.GET.get('marca')
    # buscar_modelo = request.GET.get('modelo')
    
    # # Filtrar según los parámetros proporcionados, si existen
    # if buscar_marca and buscar_modelo:
    #     listado_autos = Auto.objects.filter(marca__icontains=buscar_marca, modelo__icontains=buscar_modelo)
    # elif buscar_marca:  # Si solo se proporciona marca
    #     listado_autos = Auto.objects.filter(marca__icontains=buscar_marca)
    # elif buscar_modelo:  # Si solo se proporciona modelo
    #     listado_autos = Auto.objects.filter(modelo__icontains=buscar_modelo)
    # else:  # Si no se proporciona ningún filtro, traer todos los autos
    #     listado_autos = Auto.objects.all()
    
    # Opcion 4 - UTILIZANDO LOS FORMULARIOS DE DJANGO
    
def listado_autos(request):
    
    formulario_busqueda = BuscarAuto(request.GET or None)

    if formulario_busqueda.is_valid():
        marca_a_buscar = formulario_busqueda.cleaned_data.get('marca', '')
        modelo_a_buscar = formulario_busqueda.cleaned_data.get('modelo', '')
        resultado_autos = Auto.objects.filter(
            marca__icontains=marca_a_buscar, 
            modelo__icontains=modelo_a_buscar
        )
    else:
        resultado_autos = []

    return render(request, 'inicio/listado_autos.html', {
        'listado_autos': resultado_autos, 
        'formulario': formulario_busqueda
    })
    
    # --------------------------------------------------------------------------------------------
    
def ver_auto(request, id_auto):
    
    auto = Auto.objects.get(id = id_auto)
    
    return render(request, 'inicio/ver_auto.html', {'auto': auto})

# ------------------------------------------------
def eliminar_auto(request, id_auto):

    auto = Auto.objects.get(id = id_auto)
    
    auto.delete()
    
    return render(request, 'inicio/eliminar_auto.html', {'auto': auto})

# ------------------------------------------------
def editar_auto(request, id_auto):
    
    auto = Auto.objects.get(id = id_auto)
    
    formulario = EditarAuto(initial= {'marca': auto.marca
                                      , 'modelo': auto.modelo
                                      , 'anio': auto.anio})
    
    if request.method == 'POST':
        formulario = EditarAuto(request.POST)
        if formulario.is_valid():
                        
            auto.marca = formulario.cleaned_data.get('marca')
            auto.modelo = formulario.cleaned_data.get('modelo')
            auto.anio = formulario.cleaned_data.get('anio')
        
            auto.save()
            
            return redirect ('inicio:listado_autos.html')
      
    return render(request, 'inicio/editar_auto.html', {'formulario': formulario, 'auto': auto})

inicio/templates/inicio/auto_correctamente_creado.html
{% extends "base.html" %}

{% block title_head %}
Auto Correctamente Creado
{% endblock title_head %}

{% block h1_header %}
Auto Correctamente Creado
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %} {% endcomment %}
{% block main %}
<h1>Run Run</h1>
<p>Listo el auto {{auto}}. Se creó correctamente </p>
{% endblock main %}

inicio/templates/inicio/bienvenida.html
{% extends "base.html" %}

{% block title_head %}
Bienvenida
{% endblock title_head %}

{% block h1_header %}
Bienvenida
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %} {% endcomment %}

{% block main %}
<h1>Bienvenida</h1>
<p>Welcome - Bienvenu - Bem Vindo - Benvenuto - Dobro Pazhalobat</p>
{% endblock main %}

inicio/templates/inicio/condicional_loop.html
{% extends "base.html" %}

{% block title_head %}
Condicional_Loop
{% endblock title_head %}

{% block h1_header %}
Condicional_Loop
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %} {% endcomment %}

{% block main %}
<h1>Hola, soy el condicional y loop</h1>
<p>Hola, soy el parrafo de condicional y loop</p>
{% endblock main %}

-----------------------------------------------------------------------------------------

{% if mis_elementos %}  

<p> Mi lista tiene valores </p>

{% else %}

<p> Mi lista NO tiene valores </p>
{% endif %}
-----------------------------------------------------------------------------------------    

{% if numeros|length > 10 %}  

<ul>
    {% for numero in numeros %}
    <li>
        {{numero}}
    </li>
    {% endfor %} 
  
</ul>
{% endif %}
    
-----------------------------------------------------------------------------------------

inicio/templates/inicio/crear_auto.html
{% extends "base.html" %}

{% block title_head %}
Crear Auto
{% endblock title_head %}

{% block h1_header %}
Crear Auto
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %}  {% endcomment %}

{% block main %}
{% comment %}
Por un tema de seguridad se activa el CSRF token. Sin esto el post no puede funcionar
{% endcomment %}

{% comment %} <form action={% url "inicio:crear_auto" %} method = "get">  {% endcomment %}
<form action={% url "inicio:crear_auto" %} method = "post">
    {% csrf_token %}

{% comment %} 
<form action={% url "inicio:crear_auto" %} method = "get">  
es recomendable hacerlo por post porque protege mejor la información 
<p>
    marca
    <input type="text" name= 'marca' placeholder = 'marca'>
</p>
<p>
    modelo
    <input type="text" name= 'modelo' placeholder = 'modelo'>
</p> 
<p>
    anio
    <input type="number" name= 'anio' placeholder = 'anio'>
    {% comment %} tiene que ir excrito exactamente igual a lo que sale en el view 
</p> 
    {% endcomment %}

    {% comment %}  el formulario que se manda por contexto {% endcomment %}

    {{formulario}} 
    <input type="submit" value = 'Enviar Formulario'>
    {% comment %} <button> Enviar Formulario </button>  {% endcomment %} 

</form>
{% endblock main %}

inicio/templates/inicio/editar_auto.html
{% extends "base.html" %}

{% block title_head %}
Editar Auto
{% endblock title_head %}

{% block h1_header %}
Editar Auto
{% endblock h1_header %}

{% block main %}

<form action={% url "inicio:editar_auto" auto.id %} method = "post">
    {% csrf_token %}

    {{formulario}} 
    <input type="submit" value = 'Editar'>
    {% comment %} <button> Enviar Formulario </button>  {% endcomment %} 

</form>
{% endblock main %}

inicio/templates/inicio/eliminar_auto.html
{% extends "base.html" %} 

{% block title_head %} 

Eliminar 

{% endblock title_head %}
\ 

{% block h1_header %}

Se eliminó el auto {{auto}}

{% endblock h1_header %} 

inicio/templates/inicio/home.html
{% extends "base.html" %}

{% block title_head %}
Inicio
{% endblock title_head %}

{% block h1_header %}
Inicio
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %} {% endcomment %}

inicio/templates/inicio/listado_autos.html
{% extends "base.html" %}

{% block title_head %}
Autos
{% endblock title_head %}
{% block h1_header %}Listado de autos{% endblock h1_header %}

{% block main %}

<a href={% url "inicio:crear_auto" %}>Crear Auto</a>

<p>
    <form action={% url "inicio:listado_autos" %}>
        
        {% comment %} # v1 y v2
        <input type="text" name='marca' placeholder='Ford, Fiat, Chevrolet...'>
        <input type="text" name='modelo' placeholder='Uno, K, 206...'> {% endcomment %}
        {{formulario}}
    
        <input type="submit" value='Buscar'>
    
    </form>
</p>
{% if listado_autos %}
<ul>
    {% for auto in listado_autos %}
    <li>
        {{ auto.marca }} {{ auto.modelo }} ({{ auto.anio }})
        | <a href="{% url 'inicio:ver_auto' auto.id %}">Ver</a>
        | <a href="{% url 'inicio:editar_auto' auto.id %}">Editar</a>
        | <a href="{% url 'inicio:eliminar_auto' auto.id %}">Eliminar</a>  
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No se encontraron autos con esos criterios.</p>
{% endif %}

{% endblock main %}

inicio/templates/inicio/mitemplate.html
{% extends "base.html" %}

{% block title_head %}
Mi template
{% endblock title_head %}

{% block h1_header %}
Mi template
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %} {% endcomment %}

{% block main %}
<h1>Hola, soy el título de mi template</h1>
<p>Hola, soy el parrafo de mi template</p>
{% endblock main %}

inicio/templates/inicio/mitemplate2.html
{% extends "base.html" %}

{% block title_head %}
Mi 2do template
{% endblock title_head %}

{% block h1_header %}
Mi 2do template
{% endblock h1_header %}

{% comment %} {% block header %}
Inicio - Inicio
{% endblock header %} {% endcomment %}

{% block main %}
<h1>Hola, soy el título de mi SEGUNDO template</h1>
<p>Hola, soy el parrafo de mi template</p>
{% endblock main %}

inicio/templates/inicio/ver_auto.html
{% extends "base.html" %} 

{% block title_head %} 
Auto {% endblock title_head %}
\ 

{% block h1_header %}

{{auto}}

{% endblock h1_header %} 


{% block main %}
<ul>
<li>Marca: {{auto.marca}}</li>
<li>Modelo: {{auto.modelo}}</li>
<li>Anio: {{auto.anio}}</li>


</ul>

{% endblock main %}