inicio/urls.py
# De esta forma voy importando las funcionalidades de las views una por una, pero se puede hacer demasiado largo
# from inicio.views import bienvenida, fecha_y_hora, saludo, mitemplate, mitemplate2, condicional_loop, crear_auto, home, listado_autos

#Esta forma es más práctica
from inicio import views    # sólo tengo qyue agregar views a los urls
from django.urls import path

app_name = 'inicio' # creo esta variable para luego acomodar el tema de los links. Esta variable contiene el nombre de mi aplicacion
                    # y la modificacion se hace sobre el urls.py propio de la aplicación. 

urlpatterns = [
    path('bienvenida', views.bienvenida, name = 'bienvenida'),
    path('', views.home, name = 'home'),
    path('fecha-y-hora/', views.fecha_y_hora,name = 'datetime'),
    path('saludo/<nombre>/<apellido>/', views.saludo, name = 'saludo'), 
    path('mitemplate/', views.mitemplate, name = 'mitemplate'),
    path('mitemplate2/', views.mitemplate2, name = 'mitemplate2'),
    path('condicional_loop/', views.condicional_loop, name = 'condicional_loop'),
    #,path('crear_auto/<str:marca>/<str:modelo>/<int:anio>', crear_auto, name = 'crear_auto') # opcion 1
    path('autos/', views.listado_autos, name='listado_autos')
    ,path('autos/crear', views.crear_auto, name = 'crear_auto')
    ,path('autos/<int:id_auto>', views.ver_auto, name = 'ver_auto')
    ,path('autos/<int:id_auto>/eliminar', views.eliminar_auto, name = 'eliminar_auto')
    ,path('autos/<int:id_auto>/editar', views.editar_auto, name = 'editar_auto')
  
    ]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include

# aca puedo ver la modificacion automatica que se hizo cuando cambié la carpeta de lugar
# el tema es que me lo trae automaticamente como ..inicio.views (dos carpetas por arriba de inicio) y yo necesito que sea directo
#desde inicio, y por eso queda finalmente: inicio.views (ver aquí abajo)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("inicio.urls"))    # include el nombre de la aplicacion (inicio) y el archivo donde tengo los "links" (urls)
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head %}
            Base
            {% endblock title_head %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url "inicio:home"%}>home</a>
                <a class="navbar-brand" href={% url "inicio:bienvenida"%}>Bienvenida</a>
                {% comment %} <a class="navbar-brand" href={% url "inicio:mitemplate2"%}>MiTemplate2</a> {% endcomment %}
                <a class="navbar-brand" href={% url "inicio:crear_auto"%}>Crear Auto</a>
                <a class="navbar-brand" href={% url "inicio:listado_autos"%}>Listado de Autos</a>
                {%comment%} <a class="btn btn-primary" href="#signup">Sign Up</a> {%endcomment%}
            </div>
        </nav>
        <!-- Masthead-->
         {% block header%}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">{%block h1_header%} Base {%endblock h1_header%}</h1>
                          </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header%}
        <main>
            {% block main %}

            {% endblock main%}
        </main>
        <!-- Icons Grid-->
        <!-- Image Showcases-->
        <section class="showcase">
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/condicional_loop.html
<h1> este es el html de condicionales y bucles </h1>

<p>
{{pepito}}
</p>